version: '3.7'
services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins-net:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - '2376:2376'

  jenkins-blueocean:
    image: jenkinsci/blueocean
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - $$HOME:/home
    ports:
      - '8080:8080'
    networks:
      - jenkins-net
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins-net:
